stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apt install -y curl
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=<tag> "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
  environment: production