label:
  de: SEO
  en: SEO

fields:
  head_title:
    extends: head/head_title

  head_author:
    extends: head/head_author
    width: 1/2

  head_keywords:
    extends: head/head_keywords
    width: 1/2

  head_description:
    extends: head/head_description

  head_google_site_verification:
    extends: head/head_google_site_verification
    width: 1/3

  head_google_tag_toggle:
    extends: head/head_google_tag_toggle
    width: 1/3

  head_google_tag:
    extends: head/head_google_tag
    width: 1/3
    when:
      head_google_tag_toggle: true

  head_google_tag_manager:
    extends: head/head_google_tag_manager
    width: 1/3
    when:
      head_google_tag_toggle: false

  line1:
    type: line

  head_og_site_name:
    extends: head/head_og_site_name
    width: 1/2

  head_og_image:
    extends: head/head_og_image
    width: 1/2

  line2:
    type: line

  head_twitter_site:
    extends: head/head_twitter_site
    width: 1/2

  head_twitter_image:
    extends: head/head_twitter_image
    width: 1/2
