label:
  de: SEO & Social Media
  en: SEO & Social Media

fields:
  head_author:
    extends: fields/head_author
    width: 1/2

  head_google_site_verification:
    extends: fields/head_google_site_verification
    width: 1/2

  head_keywords:
    extends: fields/head_keywords
    width: 1/2

  line1:
    type: line

  head_og_image:
    extends: fields/head_og_image
    width: 1/2

  line2:
    type: line

  head_twitter_site:
    extends: fields/head_twitter_site
    width: 1/2

  head_twitter_image:
    extends: fields/head_twitter_image
    width: 1/2

  line3:
    type: line

  favicon_info:
    label:
      de: Hinweis
      en: Notice
    type: info
    text: TODO
